### ISSUE TITLE
Corrección

### ISSUE THREAD

**Issue by JaviGomez02** [JaviGomez02/Tercer-Trimestre-Programacion#1]
Ya está terminado el ejercicio Pueblos Provincias para que me lo corrijas.

**Comment by ioliasa** [comment]
En el constructor de prueblo usa los set que has creado, si no lo usas puedes darle un valor negativo al número de habitantes, a la renta per cápita y a la superficie.
En provincia:
 existePueblo: debe salirse cuando encuentre el pueblo
delPueblo, setNumeroHabitantes, getInformaciónPueblo debe salirse cuando encuentre el pueblo.
numPueblos: debes usar el size.
